export const weatherDescriptionTranslations = {
  clearSky: "céu limpo",
  fewClouds: "poucas nuvens",
  scatteredClouds: "nuvens dispersas",
  brokenClouds: "nuvens quebradas",
  showerRain: "chuva leve",
  rain: "chuva",
  thunderstorm: "tempestade",
  snow: "neve",
  mist: "nevoeiro",
  smoke: "fumaça",
  haze: "névoa",
  dust: "poeira",
  fog: "neblina",
  sand: "areia",
  ash: "cinzas",
  squalls: "ventania",
  tornado: "tornado",
};
